{
    'name': 'Company Profile',
    'version': '1.2',
    'summary': 'Quản lý thông tin doanh nghiệp',
    'description': 'Module dùng để lưu trữ và quản lý hồ sơ công ty như tên, mã số thuế, lĩnh vực hoạt động...',
    'category': 'Custom',
    'author': 'Mỹ Tiên',
    'website': 'https://mekongpetro.com/',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
