#version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:17.4
    container_name: odoo_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo_postgres_data:/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - odoo_network

  # Odoo Service
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo_app
    depends_on:
      - postgres
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./custom_modules:/mnt/custom_modules
      - ./logs:/var/log/odoo
      - ./geoip:/usr/share/geoip
      - ./odoo.conf.template:/etc/odoo/odoo.conf.template
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: always
    networks:
      - odoo_network

volumes:
  odoo_postgres_data:
  odoo_data:

networks:
  odoo_network:
